name: hack
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.14
  go_router: ^11.1.4
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  gradient_borders: ^1.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: VTB Group UI
      fonts:
        - asset: assets/fonts/VTBGroupUI-Regular.ttf
